module GameInterface {
		
	interface GameServer
	{	

		string createPlayerAccount(in string firstNameParam, in string lastNameParam, in string usernameParam,in string passwordParam,in long ageParam, in string iPAdressParam);
		string playerSignIn(in string usernameParam, in string passwordParam,in string iPAdressParam);
		string playerSignOut(in string usernameParam,in  string iPAdressParam);
		string transferAccount (in string usernameParam,in string passwordParam,in string oldIPAddressParam,in string newIPAddressParam);
		
		string getPlayerStatus(in string adminUsernameParam, in string adminPasswordParam, in string iPAdressParam);
		string suspendAccount(in string adminUsernameParam, in string adminPasswordParam, in string iPAdressParam, in string usernameToSuspendParam);
			
	};
	
};
